valve.line.input.from.superiorres=XV1
valve.line.upstream=XV2
valve.line.downstream=XV3
valve.airpurge=XV4
valve.pressurereg=XV5
valve.feed.to.inferiorres=XV6
valve.dn32=XV7
valve.dn08=XV8
valve.dn02=XV9
valve.ramal1=XV10
valve.ramal2=XV11
valve.ramal3=XV12
valve.ramal4=XV13
valve.ramal5=XV14
valve.ramal6=XV15
valve.ramal7=XV16
valve.ramal8=XV17
valve.ramal9=XV18
valve.ramal10=XV19
valve.diversor=XV20
valve.scale.container=XV21

meter.reference.dn32=HSCFTA
meter.reference.dn08=HSCFTM
meter.reference.dn02=HSCFTB

temp.sensor.line.upstream=TTLI
temp.sensor.line.downstream=TTLO
temp.sensor.scale=TTWL
temp.sensor.reserv.inf=TTRI
temp.sensor.reserv.sup=TTRS
temp.sensor.amb=TTAMB


press.sensor.line.upstream=PTLI
press.sensor.line.downstream=PTLO
press.sensor.dif=PTDIF
press.sensor.barometric=PTBAR

level.sensor.inferiorres.low=SN1
level.sensor.inferiorres.mid=SN2
level.sensor.inferiorres.high=SN3
level.sensor.superiorres.high=SN4

humidity.sensor.tag=TRH

line.tag=LINHAF

pump.bp1.tag=BP1
pump.bp2.tag=BP2
pump.brep.tag=BREP

ramal1=RML1
ramal2=RML2
ramal3=RML3
ramal4=RML4
ramal5=RML5
ramal6=RML6
ramal7=RML7
ramal8=RML8
ramal9=RML9
ramal10=RML10
