command=command
field.stop.val=stop
field.ack.val=ackResponse
field.nack.val=nackResponse

field.sensorsel=sensorSel
field.tempread=tempRead
field.tempread=pressureRead

field.getsensortemp.val=getSensorTemp
field.getsensorpressure.val=getSensorPressure
field.getsensorlevel.val=getSensorLevel
field.getsensorhumidity.val=getSensorHumidity
field.reset.val=reset


field.openline.val=openLine
field.closeline.val=closeLine
field.getlinestate.val=getLineState
field.setflowrate.val=setFlowRate
field.startcounter.val=startCounter
field.stopcounter.val=stopCounter
field.getcounter.val=getCounter

field.setpidparameters.val=setPidParameters
field.getpidparameters.val=getPidParameters

field.openvalve.val=openValve
field.closevalve.val=closeValve
field.getvalvestate.val=getValveState

field.setpumpload.val=setPumpLoad
field.getpumpload.val=getPumpLoad
field.getpumpstate.val=getPumpState

field.readflowraterefmeter.val=readFlowRateRefMeter 
field.readvolumerefmeter.val=readVolumeRefMeter
field.readrefmeter.val=readRefMeter

field.setenablebuffer.val=setEnableBuffer
field.startpump.val=startPump
field.stoppump.val=stopPump

field.getscaleweight.val=getScaleWeight

field.setautoflowrate.val=setAutoFlowRate

field.getalarms.val=getAlarms

date.format=yyyy-MM-dd HH:mm:ss.SSS


